export const getFlagEmoji = (countryCode: string) => {
    return countryCode
        .toUpperCase()
        .replace(/./g, (char) => String.fromCodePoint(char.charCodeAt(0) + 127397));
};

export const countries = [
    { name: "Afghanistan", code: "AF", emoji: "🇦🇫", dial: "+93" },
    { name: "Albania", code: "AL", emoji: "🇦🇱", dial: "+355" },
    { name: "Algeria", code: "DZ", emoji: "🇩🇿", dial: "+213" },
    { name: "American Samoa", code: "AS", emoji: "🇦🇸", dial: "+1684" },
    { name: "Andorra", code: "AD", emoji: "🇦🇩", dial: "+376" },
    { name: "Angola", code: "AO", emoji: "🇦🇴", dial: "+244" },
    { name: "Anguilla", code: "AI", emoji: "🇦🇮", dial: "+1264" },
    { name: "Antarctica", code: "AQ", emoji: "🇦🇶", dial: "+672" },
    { name: "Antigua and Barbuda", code: "AG", emoji: "🇦🇬", dial: "+1268" },
    { name: "Argentina", code: "AR", emoji: "🇦🇷", dial: "+54" },
    { name: "Armenia", code: "AM", emoji: "🇦🇲", dial: "+374" },
    { name: "Aruba", code: "AW", emoji: "🇦🇼", dial: "+297" },
    { name: "Australia", code: "AU", emoji: "🇦🇺", dial: "+61" },
    { name: "Austria", code: "AT", emoji: "🇦🇹", dial: "+43" },
    { name: "Azerbaijan", code: "AZ", emoji: "🇦🇿", dial: "+994" },
    { name: "Bahamas", code: "BS", emoji: "🇧🇸", dial: "+1242" },
    { name: "Bahrain", code: "BH", emoji: "🇧🇭", dial: "+973" },
    { name: "Bangladesh", code: "BD", emoji: "🇧🇩", dial: "+880" },
    { name: "Barbados", code: "BB", emoji: "🇧🇧", dial: "+1246" },
    { name: "Belarus", code: "BY", emoji: "🇧🇾", dial: "+375" },
    { name: "Belgium", code: "BE", emoji: "🇧🇪", dial: "+32" },
    { name: "Belize", code: "BZ", emoji: "🇧🇿", dial: "+501" },
    { name: "Benin", code: "BJ", emoji: "🇧🇯", dial: "+229" },
    { name: "Bermuda", code: "BM", emoji: "🇧🇲", dial: "+1441" },
    { name: "Bhutan", code: "BT", emoji: "🇧🇹", dial: "+975" },
    { name: "Bolivia", code: "BO", emoji: "🇧🇴", dial: "+591" },
    { name: "Bosnia and Herzegovina", code: "BA", emoji: "🇧🇦", dial: "+387" },
    { name: "Botswana", code: "BW", emoji: "🇧🇼", dial: "+267" },
    { name: "Brazil", code: "BR", emoji: "🇧🇷", dial: "+55" },
    { name: "British Indian Ocean Territory", code: "IO", emoji: "🇮🇴", dial: "+246" },
    { name: "Brunei Darussalam", code: "BN", emoji: "🇧🇳", dial: "+673" },
    { name: "Bulgaria", code: "BG", emoji: "🇧🇬", dial: "+359" },
    { name: "Burkina Faso", code: "BF", emoji: "🇧🇫", dial: "+226" },
    { name: "Burundi", code: "BI", emoji: "🇧🇮", dial: "+257" },
    { name: "Cambodia", code: "KH", emoji: "🇰🇭", dial: "+855" },
    { name: "Cameroon", code: "CM", emoji: "🇨🇲", dial: "+237" },
    { name: "Canada", code: "CA", emoji: "🇨🇦", dial: "+1" },
    { name: "Cape Verde", code: "CV", emoji: "🇨🇻", dial: "+238" },
    { name: "Cayman Islands", code: "KY", emoji: "🇰🇾", dial: "+1345" },
    { name: "Central African Republic", code: "CF", emoji: "🇨🇫", dial: "+236" },
    { name: "Chad", code: "TD", emoji: "🇹🇩", dial: "+235" },
    { name: "Chile", code: "CL", emoji: "🇨🇱", dial: "+56" },
    { name: "China", code: "CN", emoji: "🇨🇳", dial: "+86" },
    { name: "Christmas Island", code: "CX", emoji: "🇨🇽", dial: "+61" },
    { name: "Cocos (Keeling) Islands", code: "CC", emoji: "🇨🇨", dial: "+61" },
    { name: "Colombia", code: "CO", emoji: "🇨🇴", dial: "+57" },
    { name: "Comoros", code: "KM", emoji: "🇰🇲", dial: "+269" },
    { name: "Congo", code: "CG", emoji: "🇨🇬", dial: "+242" },
    { name: "Congo, The Democratic Republic of the", code: "CD", emoji: "🇨🇩", dial: "+243" },
    { name: "Cook Islands", code: "CK", emoji: "🇨🇰", dial: "+682" },
    { name: "Costa Rica", code: "CR", emoji: "🇨🇷", dial: "+506" },
    { name: "Cote D'Ivoire", code: "CI", emoji: "🇨🇮", dial: "+225" },
    { name: "Croatia", code: "HR", emoji: "🇭🇷", dial: "+385" },
    { name: "Cuba", code: "CU", emoji: "🇨🇺", dial: "+53" },
    { name: "Cyprus", code: "CY", emoji: "🇨🇾", dial: "+357" },
    { name: "Czech Republic", code: "CZ", emoji: "🇨🇿", dial: "+420" },
    { name: "Denmark", code: "DK", emoji: "🇩🇰", dial: "+45" },
    { name: "Djibouti", code: "DJ", emoji: "🇩🇯", dial: "+253" },
    { name: "Dominica", code: "DM", emoji: "🇩🇲", dial: "+1767" },
    { name: "Dominican Republic", code: "DO", emoji: "🇩🇴", dial: "+1849" },
    { name: "Ecuador", code: "EC", emoji: "🇪🇨", dial: "+593" },
    { name: "Egypt", code: "EG", emoji: "🇪🇬", dial: "+20" },
    { name: "El Salvador", code: "SV", emoji: "🇸🇻", dial: "+503" },
    { name: "Equatorial Guinea", code: "GQ", emoji: "🇬🇶", dial: "+240" },
    { name: "Eritrea", code: "ER", emoji: "🇪🇷", dial: "+291" },
    { name: "Estonia", code: "EE", emoji: "🇪🇪", dial: "+372" },
    { name: "Ethiopia", code: "ET", emoji: "🇪🇹", dial: "+251" },
    { name: "Falkland Islands (Malvinas)", code: "FK", emoji: "🇫🇰", dial: "+500" },
    { name: "Faroe Islands", code: "FO", emoji: "🇫🇴", dial: "+298" },
    { name: "Fiji", code: "FJ", emoji: "🇫🇯", dial: "+679" },
    { name: "Finland", code: "FI", emoji: "🇫🇮", dial: "+358" },
    { name: "France", code: "FR", emoji: "🇫🇷", dial: "+33" },
    { name: "French Guiana", code: "GF", emoji: "🇬🇫", dial: "+594" },
    { name: "French Polynesia", code: "PF", emoji: "🇵🇫", dial: "+689" },
    { name: "French Southern Territories", code: "TF", emoji: "🇹🇫", dial: "+262" },
    { name: "Gabon", code: "GA", emoji: "🇬🇦", dial: "+241" },
    { name: "Gambia", code: "GM", emoji: "🇬🇲", dial: "+220" },
    { name: "Georgia", code: "GE", emoji: "🇬🇪", dial: "+995" },
    { name: "Germany", code: "DE", emoji: "🇩🇪", dial: "+49" },
    { name: "Ghana", code: "GH", emoji: "🇬🇭", dial: "+233" },
    { name: "Gibraltar", code: "GI", emoji: "🇬🇮", dial: "+350" },
    { name: "Greece", code: "GR", emoji: "🇬🇷", dial: "+30" },
    { name: "Greenland", code: "GL", emoji: "🇬🇱", dial: "+299" },
    { name: "Grenada", code: "GD", emoji: "🇬🇩", dial: "+1473" },
    { name: "Guadeloupe", code: "GP", emoji: "🇬🇵", dial: "+590" },
    { name: "Guam", code: "GU", emoji: "🇬🇺", dial: "+1671" },
    { name: "Guatemala", code: "GT", emoji: "🇬🇹", dial: "+502" },
    { name: "Guinea", code: "GN", emoji: "🇬🇳", dial: "+224" },
    { name: "Guinea-Bissau", code: "GW", emoji: "🇬🇼", dial: "+245" },
    { name: "Guyana", code: "GY", emoji: "🇬🇾", dial: "+592" },
    { name: "Haiti", code: "HT", emoji: "🇭🇹", dial: "+509" },
    { name: "Heard Island and Mcdonald Islands", code: "HM", emoji: "🇭🇲", dial: "+672" },
    { name: "Holy See (Vatican City State)", code: "VA", emoji: "🇻🇦", dial: "+379" },
    { name: "Honduras", code: "HN", emoji: "🇭🇳", dial: "+504" },
    { name: "Hong Kong", code: "HK", emoji: "🇭🇰", dial: "+852" },
    { name: "Hungary", code: "HU", emoji: "🇭🇺", dial: "+36" },
    { name: "Iceland", code: "IS", emoji: "🇮🇸", dial: "+354" },
    { name: "India", code: "IN", emoji: "🇮🇳", dial: "+91" },
    { name: "Indonesia", code: "ID", emoji: "🇮🇩", dial: "+62" },
    { name: "Iran, Islamic Republic of", code: "IR", emoji: "🇮🇷", dial: "+98" },
    { name: "Iraq", code: "IQ", emoji: "🇮🇶", dial: "+964" },
    { name: "Ireland", code: "IE", emoji: "🇮🇪", dial: "+353" },
    { name: "Israel", code: "IL", emoji: "🇮🇱", dial: "+972" },
    { name: "Italy", code: "IT", emoji: "🇮🇹", dial: "+39" },
    { name: "Jamaica", code: "JM", emoji: "🇯🇲", dial: "+1876" },
    { name: "Japan", code: "JP", emoji: "🇯🇵", dial: "+81" },
    { name: "Jordan", code: "JO", emoji: "🇯🇴", dial: "+962" },
    { name: "Kazakhstan", code: "KZ", emoji: "🇰🇿", dial: "+7" },
    { name: "Kenya", code: "KE", emoji: "🇰🇪", dial: "+254" },
    { name: "Kiribati", code: "KI", emoji: "🇰🇮", dial: "+686" },
    { name: "Korea, Democratic People's Republic of", code: "KP", emoji: "🇰🇵", dial: "+850" },
    { name: "Korea, Republic of", code: "KR", emoji: "🇰🇷", dial: "+82" },
    { name: "Kuwait", code: "KW", emoji: "🇰🇼", dial: "+965" },
    { name: "Kyrgyzstan", code: "KG", emoji: "🇰🇬", dial: "+996" },
    { name: "Lao People's Democratic Republic", code: "LA", emoji: "🇱🇦", dial: "+856" },
    { name: "Latvia", code: "LV", emoji: "🇱🇻", dial: "+371" },
    { name: "Lebanon", code: "LB", emoji: "🇱🇧", dial: "+961" },
    { name: "Lesotho", code: "LS", emoji: "🇱🇸", dial: "+266" },
    { name: "Liberia", code: "LR", emoji: "🇱🇷", dial: "+231" },
    { name: "Libyan Arab Jamahiriya", code: "LY", emoji: "🇱🇾", dial: "+218" },
    { name: "Liechtenstein", code: "LI", emoji: "🇱🇮", dial: "+423" },
    { name: "Lithuania", code: "LT", emoji: "🇱🇹", dial: "+370" },
    { name: "Luxembourg", code: "LU", emoji: "🇱🇺", dial: "+352" },
    { name: "Macao", code: "MO", emoji: "🇲🇴", dial: "+853" },
    { name: "Macedonia, The Former Yugoslav Republic of", code: "MK", emoji: "🇲🇰", dial: "+389" },
    { name: "Madagascar", code: "MG", emoji: "🇲🇬", dial: "+261" },
    { name: "Malawi", code: "MW", emoji: "🇲🇼", dial: "+265" },
    { name: "Malaysia", code: "MY", emoji: "🇲🇾", dial: "+60" },
    { name: "Maldives", code: "MV", emoji: "🇲🇻", dial: "+960" },
    { name: "Mali", code: "ML", emoji: "🇲🇱", dial: "+223" },
    { name: "Malta", code: "MT", emoji: "🇲🇹", dial: "+356" },
    { name: "Marshall Islands", code: "MH", emoji: "🇲🇭", dial: "+692" },
    { name: "Martinique", code: "MQ", emoji: "🇲🇶", dial: "+596" },
    { name: "Mauritania", code: "MR", emoji: "🇲🇷", dial: "+222" },
    { name: "Mauritius", code: "MU", emoji: "🇲🇺", dial: "+230" },
    { name: "Mayotte", code: "YT", emoji: "🇾🇹", dial: "+262" },
    { name: "Mexico", code: "MX", emoji: "🇲🇽", dial: "+52" },
    { name: "Micronesia, Federated States of", code: "FM", emoji: "🇫🇲", dial: "+691" },
    { name: "Moldova, Republic of", code: "MD", emoji: "🇲🇩", dial: "+373" },
    { name: "Monaco", code: "MC", emoji: "🇲🇨", dial: "+377" },
    { name: "Mongolia", code: "MN", emoji: "🇲🇳", dial: "+976" },
    { name: "Montserrat", code: "MS", emoji: "🇲🇸", dial: "+1664" },
    { name: "Morocco", code: "MA", emoji: "🇲🇦", dial: "+212" },
    { name: "Mozambique", code: "MZ", emoji: "🇲🇿", dial: "+258" },
    { name: "Myanmar", code: "MM", emoji: "🇲🇲", dial: "+95" },
    { name: "Namibia", code: "NA", emoji: "🇳🇦", dial: "+264" },
    { name: "Nauru", code: "NR", emoji: "🇳🇷", dial: "+674" },
    { name: "Nepal", code: "NP", emoji: "🇳🇵", dial: "+977" },
    { name: "Netherlands", code: "NL", emoji: "🇳🇱", dial: "+31" },
    { name: "Netherlands Antilles", code: "AN", emoji: "🇦🇳", dial: "+599" },
    { name: "New Caledonia", code: "NC", emoji: "🇳🇨", dial: "+687" },
    { name: "New Zealand", code: "NZ", emoji: "🇳🇿", dial: "+64" },
    { name: "Nicaragua", code: "NI", emoji: "🇳🇮", dial: "+505" },
    { name: "Niger", code: "NE", emoji: "🇳🇪", dial: "+227" },
    { name: "Nigeria", code: "NG", emoji: "🇳🇬", dial: "+234" },
    { name: "Niue", code: "NU", emoji: "🇳🇺", dial: "+683" },
    { name: "Norfolk Island", code: "NF", emoji: "🇳🇫", dial: "+672" },
    { name: "Northern Mariana Islands", code: "MP", emoji: "🇲🇵", dial: "+1670" },
    { name: "Norway", code: "NO", emoji: "🇳🇴", dial: "+47" },
    { name: "Oman", code: "OM", emoji: "🇴🇲", dial: "+968" },
    { name: "Pakistan", code: "PK", emoji: "🇵🇰", dial: "+92" },
    { name: "Palau", code: "PW", emoji: "🇵🇼", dial: "+680" },
    { name: "Palestinian Territory, Occupied", code: "PS", emoji: "🇵🇸", dial: "+970" },
    { name: "Panama", code: "PA", emoji: "🇵🇦", dial: "+507" },
    { name: "Papua New Guinea", code: "PG", emoji: "🇵🇬", dial: "+675" },
    { name: "Paraguay", code: "PY", emoji: "🇵🇾", dial: "+595" },
    { name: "Peru", code: "PE", emoji: "🇵🇪", dial: "+51" },
    { name: "Philippines", code: "PH", emoji: "🇵🇭", dial: "+63" },
    { name: "Pitcairn", code: "PN", emoji: "🇵🇳", dial: "+870" },
    { name: "Poland", code: "PL", emoji: "🇵🇱", dial: "+48" },
    { name: "Portugal", code: "PT", emoji: "🇵🇹", dial: "+351" },
    { name: "Puerto Rico", code: "PR", emoji: "🇵🇷", dial: "+1939" },
    { name: "Qatar", code: "QA", emoji: "🇶🇦", dial: "+974" },
    { name: "Reunion", code: "RE", emoji: "🇷🇪", dial: "+262" },
    { name: "Romania", code: "RO", emoji: "🇷🇴", dial: "+40" },
    { name: "Russian Federation", code: "RU", emoji: "🇷🇺", dial: "+7" },
    { name: "Rwanda", code: "RW", emoji: "🇷🇼", dial: "+250" },
    { name: "Saint Helena", code: "SH", emoji: "🇸🇭", dial: "+290" },
    { name: "Saint Kitts and Nevis", code: "KN", emoji: "🇰🇳", dial: "+1869" },
    { name: "Saint Lucia", code: "LC", emoji: "🇱🇨", dial: "+1758" },
    { name: "Saint Pierre and Miquelon", code: "PM", emoji: "🇵🇲", dial: "+508" },
    { name: "Saint Vincent and the Grenadines", code: "VC", emoji: "🇻🇨", dial: "+1784" },
    { name: "Samoa", code: "WS", emoji: "🇼🇸", dial: "+685" },
    { name: "San Marino", code: "SM", emoji: "🇸🇲", dial: "+378" },
    { name: "Sao Tome and Principe", code: "ST", emoji: "🇸🇹", dial: "+239" },
    { name: "Saudi Arabia", code: "SA", emoji: "🇸🇦", dial: "+966" },
    { name: "Senegal", code: "SN", emoji: "🇸🇳", dial: "+221" },
    { name: "Serbia and Montenegro", code: "CS", emoji: "🇨🇸", dial: "+381" },
    { name: "Seychelles", code: "SC", emoji: "🇸🇨", dial: "+248" },
    { name: "Sierra Leone", code: "SL", emoji: "🇸🇱", dial: "+232" },
    { name: "Singapore", code: "SG", emoji: "🇸🇬", dial: "+65" },
    { name: "Slovakia", code: "SK", emoji: "🇸🇰", dial: "+421" },
    { name: "Slovenia", code: "SI", emoji: "🇸🇮", dial: "+386" },
    { name: "Solomon Islands", code: "SB", emoji: "🇸🇧", dial: "+677" },
    { name: "Somalia", code: "SO", emoji: "🇸🇴", dial: "+252" },
    { name: "South Africa", code: "ZA", emoji: "🇿🇦", dial: "+27" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS", emoji: "🇬🇸", dial: "+500" },
    { name: "Spain", code: "ES", emoji: "🇪🇸", dial: "+34" },
    { name: "Sri Lanka", code: "LK", emoji: "🇱🇰", dial: "+94" },
    { name: "Sudan", code: "SD", emoji: "🇸🇩", dial: "+249" },
    { name: "Suriname", code: "SR", emoji: "🇸🇷", dial: "+597" },
    { name: "Svalbard and Jan Mayen", code: "SJ", emoji: "🇸🇯", dial: "+47" },
    { name: "Swaziland", code: "SZ", emoji: "🇸🇿", dial: "+268" },
    { name: "Sweden", code: "SE", emoji: "🇸🇪", dial: "+46" },
    { name: "Switzerland", code: "CH", emoji: "🇨🇭", dial: "+41" },
    { name: "Syrian Arab Republic", code: "SY", emoji: "🇸🇾", dial: "+963" },
    { name: "Taiwan, Province of China", code: "TW", emoji: "🇹🇼", dial: "+886" },
    { name: "Tajikistan", code: "TJ", emoji: "🇹🇯", dial: "+992" },
    { name: "Tanzania, United Republic of", code: "TZ", emoji: "🇹🇿", dial: "+255" },
    { name: "Thailand", code: "TH", emoji: "🇹🇭", dial: "+66" },
    { name: "Timor-Leste", code: "TL", emoji: "🇹🇱", dial: "+670" },
    { name: "Togo", code: "TG", emoji: "🇹🇬", dial: "+228" },
    { name: "Tokelau", code: "TK", emoji: "🇹🇰", dial: "+690" },
    { name: "Tonga", code: "TO", emoji: "🇹🇴", dial: "+676" },
    { name: "Trinidad and Tobago", code: "TT", emoji: "🇹🇹", dial: "+1868" },
    { name: "Tunisia", code: "TN", emoji: "🇹🇳", dial: "+216" },
    { name: "Turkey", code: "TR", emoji: "🇹🇷", dial: "+90" },
    { name: "Turkmenistan", code: "TM", emoji: "🇹🇲", dial: "+993" },
    { name: "Turks and Caicos Islands", code: "TC", emoji: "🇹🇨", dial: "+1649" },
    { name: "Tuvalu", code: "TV", emoji: "🇹🇻", dial: "+688" },
    { name: "Uganda", code: "UG", emoji: "🇺🇬", dial: "+256" },
    { name: "Ukraine", code: "UA", emoji: "🇺🇦", dial: "+380" },
    { name: "United Arab Emirates", code: "AE", emoji: "🇦🇪", dial: "+971" },
    { name: "United Kingdom", code: "GB", emoji: "🇬🇧", dial: "+44" },
    { name: "United States", code: "US", emoji: "🇺🇸", dial: "+1" },
    { name: "United States Minor Outlying Islands", code: "UM", emoji: "🇺🇲", dial: "+1" },
    { name: "Uruguay", code: "UY", emoji: "🇺🇾", dial: "+598" },
    { name: "Uzbekistan", code: "UZ", emoji: "🇺🇿", dial: "+998" },
    { name: "Vanuatu", code: "VU", emoji: "🇻🇺", dial: "+678" },
    { name: "Venezuela", code: "VE", emoji: "🇻🇪", dial: "+58" },
    { name: "Viet Nam", code: "VN", emoji: "🇻🇳", dial: "+84" },
    { name: "Virgin Islands, British", code: "VG", emoji: "🇻🇬", dial: "+1284" },
    { name: "Virgin Islands, U.S.", code: "VI", emoji: "🇻🇮", dial: "+1340" },
    { name: "Wallis and Futuna", code: "WF", emoji: "🇼🇫", dial: "+681" },
    { name: "Western Sahara", code: "EH", emoji: "🇪🇭", dial: "+212" },
    { name: "Yemen", code: "YE", emoji: "🇾🇪", dial: "+967" },
    { name: "Zambia", code: "ZM", emoji: "🇿🇲", dial: "+260" },
    { name: "Zimbabwe", code: "ZW", emoji: "🇿🇼", dial: "+263" }
];
